# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""Integration test for PR7a: validates system JSONL spans + Chrome Trace output.

Prerequisites:
    torchrun --nproc_per_node=4 torchtitan/experiments/observability/toy_spmd.py
"""

import json
import os

import pytest

OUTPUT_DIR = "/tmp/toy_spmd_output"


@pytest.fixture
def trace():
    p = os.path.join(OUTPUT_DIR, "trace.json")
    if not os.path.exists(p):
        pytest.skip("Run toy_spmd.py first")
    with open(p) as f:
        return json.load(f)


@pytest.fixture
def system_events():
    sys_dir = os.path.join(OUTPUT_DIR, "system_logs")
    if not os.path.exists(sys_dir):
        pytest.skip("Run toy_spmd.py first")
    events = []
    for f_name in os.listdir(sys_dir):
        if f_name.endswith(".jsonl"):
            with open(os.path.join(sys_dir, f_name)) as f:
                for line in f:
                    if line.strip():
                        events.append(json.loads(line))
    return events


class TestPR7aIntegration:
    def test_trace_json_exists(self):
        """trace.json should be generated by toy_spmd.py."""
        if not os.path.exists(OUTPUT_DIR):
            pytest.skip("Run toy_spmd.py first")
        assert os.path.exists(os.path.join(OUTPUT_DIR, "trace.json"))

    def test_trace_has_events(self, trace):
        """Trace should contain events."""
        assert len(trace["traceEvents"]) > 0

    def test_trace_has_fwd_bwd_spans(self, trace):
        """Trace should have fwd_bwd begin/end pairs."""
        events = trace["traceEvents"]
        span_names = {e["name"] for e in events if e.get("ph") in ("B", "E")}
        assert "fwd_bwd" in span_names

    def test_trace_has_optim_spans(self, trace):
        """Trace should have optim begin/end pairs."""
        events = trace["traceEvents"]
        span_names = {e["name"] for e in events if e.get("ph") in ("B", "E")}
        assert "optim" in span_names

    def test_trace_spans_are_paired(self, trace):
        """Every B event should have a matching E event."""
        events = trace["traceEvents"]
        begins = [(e["name"], e.get("tid")) for e in events if e.get("ph") == "B"]
        ends = [(e["name"], e.get("tid")) for e in events if e.get("ph") == "E"]
        assert len(begins) == len(ends), (
            f"Mismatched spans: {len(begins)} begins vs {len(ends)} ends"
        )

    def test_trace_has_all_4_ranks(self, trace):
        """Trace should have events from all 4 ranks."""
        events = trace["traceEvents"]
        tids = {e.get("tid") for e in events if e.get("ph") in ("B", "E")}
        assert tids == {0, 1, 2, 3}, f"Expected ranks 0-3, got {tids}"

    def test_trace_has_metric_instants(self, trace):
        """Trace should have instant events for metrics."""
        events = trace["traceEvents"]
        instants = [e for e in events if e.get("ph") == "i"]
        assert len(instants) > 0, "No metric instant events in trace"

    def test_system_jsonl_has_all_span_types(self, system_events):
        """System JSONL should have both fwd_bwd and optim spans."""
        type_names = set()
        for e in system_events:
            if "normal" in e:
                type_names.add(e["normal"].get("log_type_name", ""))
        assert "fwd_bwd_start" in type_names
        assert "fwd_bwd_end" in type_names
        assert "optim_start" in type_names
        assert "optim_end" in type_names

    def test_previous_prs_still_work(self):
        """All prior PR outputs should exist."""
        if not os.path.exists(OUTPUT_DIR):
            pytest.skip("Run toy_spmd.py first")
        assert os.path.exists(os.path.join(OUTPUT_DIR, "system_logs"))
        assert os.path.exists(os.path.join(OUTPUT_DIR, "losses.json"))
        assert os.path.exists(os.path.join(OUTPUT_DIR, "experiment_logs"))
